#!/bin/sh

. ovpn-vars.sh 

${EASYRSA_DIR}/easyrsa init-pki
${EASYRSA_DIR}/easyrsa build-ca 

${EASYRSA_DIR}/easyrsa gen-dh

# issue a bogus cert, then revoke it, so we have a CRL with one entry in it 
# (can't make a zero entry one)

echo "Creating a client cert (no pass) for the sole purpose of revoking it"

${EASYRSA_DIR}/easyrsa build-client-full boguscertforcrl nopass
${EASYRSA_DIR}/easyrsa revoke boguscertforcrl unspecified
${EASYRSA_DIR}/easyrsa gen-crl

