#!/bin/sh

EASYRSA_DIR="EasyRSA-3.1.0"

OPENVPN_SERVER_NAME="vpn2.seastrom.com"
OPENVPN_SERVER_PORT="1194"
OPENVPN_SERVER_PROTO="udp"

OPENVPN_SERVER_NAME2="vpn2.seastrom.com"
OPENVPN_SERVER_PORT2="443"
OPENVPN_SERVER_PROTO2="tcp"

#OPENVPN_SERVER_NAME3="vpn2.seastrom.com"
#OPENVPN_SERVER_PORT3="993"
#OPENVPN_SERVER_PROTO3="tcp"

